#ifndef _FSH_W_
#define _FSH_W_

#include "stm32f0xx_hal.h"
#include "pid.h"

//flash saving first address
#define CURVE_FLASH_INITIAL_ADDRESS 0x0800F800 // indirizzo prima pagina flash per temperatura
#define PID_FLASH_INITIAL_ADDRESS 0x0803FC00 // indirizzo ultima pagina per salvataggio parametri pid
#define KP_DATA_FLASH_ADDRESS PID_FLASH_INITIAL_ADDRESS
#define KI_DATA_FLASH_ADDRESS PID_FLASH_INITIAL_ADDRESS + 4
#define KD_DATA_FLASH_ADDRESS PID_FLASH_INITIAL_ADDRESS + 8

#define PREHEAT_TEMP_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS
#define PREHEAT_TIME_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS + 4
#define SOAK_TEMP_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS + 8
#define SOAK_TIME_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS + 12
#define PEAK_TEMP_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS + 16
#define REFLOW_TIME_1_ADDRESS CURVE_FLASH_INITIAL_ADDRESS + 20

#define PREHEAT_TEMP_2_ADDRESS REFLOW_TIME_1_ADDRESS + 4
#define PREHEAT_TIME_2_ADDRESS REFLOW_TIME_1_ADDRESS + 8
#define SOAK_TEMP_2_ADDRESS REFLOW_TIME_1_ADDRESS + 12
#define SOAK_TIME_2_ADDRESS REFLOW_TIME_1_ADDRESS + 16
#define PEAK_TEMP_2_ADDRESS REFLOW_TIME_1_ADDRESS + 20
#define REFLOW_TIME_2_ADDRESS REFLOW_TIME_1_ADDRESS + 24

#define PREHEAT_TEMP_3_ADDRESS REFLOW_TIME_2_ADDRESS +4
#define PREHEAT_TIME_3_ADDRESS REFLOW_TIME_2_ADDRESS + 8
#define SOAK_TEMP_3_ADDRESS REFLOW_TIME_2_ADDRESS + 12
#define SOAK_TIME_3_ADDRESS REFLOW_TIME_2_ADDRESS + 16
#define PEAK_TEMP_3_ADDRESS REFLOW_TIME_2_ADDRESS + 20
#define REFLOW_TIME_3_ADDRESS REFLOW_TIME_2_ADDRESS + 24

#define CURVE_PROFILE_BYTE_COUNT 6*sizeof(float) //numero totale byte necessari per memorizzare ogni curva

void flash_write_float(uint32_t base_address, float new_value, uint16_t offset);
float flash_read_float(uint32_t address);


#endif 